/**
 * Management Dashboard Application
 * Description for the api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GrantedAuthority } from './grantedAuthority';


export interface JwtResponse {
    accessToken?: string;
    authorities?: Array<GrantedAuthority>;
    tokenType?: string;
    username?: string;
}
